# Generated by Django 4.2.7 on 2023-11-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf_cliente', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('liquidez', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosDoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=11)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('nome_produto', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('liquidez', models.CharField(max_length=200)),
            ],
        ),
    ]
